{
  parserClass="com.zxy.ijplugin.wechat_miniprogram.lang.expr.parser.WXMLExprParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="WXMLExpr"
  psiImplClassSuffix="Impl"
  psiPackage="com.zxy.ijplugin.wechat_miniprogram.lang.expr.psi"
  psiImplPackage="com.zxy.ijplugin.wechat_miniprogram.lang.expr.psi.impl"

  elementTypeHolderClass="com.zxy.ijplugin.wechat_miniprogram.lang.expr.psi.WXMLExprTypes"
  elementTypeClass="com.zxy.ijplugin.wechat_miniprogram.lang.expr.psi.WXMLExprElementType"
  tokenTypeClass="com.zxy.ijplugin.wechat_miniprogram.lang.expr.psi.WXMLExprTokenType"

//  psiImplUtilClass="com.zxy.ijplugin.wechat_miniprogram.lang.expr.psi.impl.WXMLExprPsiImplUtils"

  tokens = [
    COMMENT = 'regexp:<!--..-->'
  ]
}

// rootObject 省略双括号
wxmlExpr ::= value | array | objectItems
operator ::= PLUS | MINUS | MULTIPLY | DIVIDE | RESIDUAL
value ::= (NUMBER | string | TRUE | FALSE | object | IDENTIFIER getValue* | valueWrap) (operator value)*
// 取值 a.b  a[b]
getValue ::= DOT IDENTIFIER | LEFT_BRACKET value RIGHT_PARENTHESES
valueWrap ::= LEFT_PARENTHESES value RIGHT_PARENTHESES
array ::= LEFT_BRACKET arrayItems RIGHT_BRACKET
arrayItems ::= (value COMMA)* value?
objectItems ::= (objectItem COMMA)* objectItem?
objectItem ::= IDENTIFIER COLON value | IDENTIFIER | EXPAND_KEYWORD value
object ::= LEFT_BRACE objectItems RIGHT_BRACE
string ::= STRING_START STRING_CONTENT STRING_END