{
  parserClass="com.zxy.ijplugin.wechat_miniprogram.lang.wxml.parser.WXMLParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="WXML"
  psiImplClassSuffix="Impl"
  psiPackage="com.zxy.ijplugin.wechat_miniprogram.lang.wxml.psi"
  psiImplPackage="com.zxy.ijplugin.wechat_miniprogram.lang.wxml.psi.impl"

  elementTypeHolderClass="com.zxy.ijplugin.wechat_miniprogram.lang.wxml.psi.WXMLTypes"
  elementTypeClass="com.zxy.ijplugin.wechat_miniprogram.lang.wxml.psi.WXMLElementType"
  tokenTypeClass="com.zxy.ijplugin.wechat_miniprogram.lang.expr.psi.WXMLExprTokenType"

//  psiImplUtilClass="com.zxy.ijplugin.wechat_miniprogram.lang.wxml.psi.impl.WXMLPsiImplUtils"

  tokens = [
    COMMENT = 'regexp:<!--..-->'
  ]
}

wxmlFile ::= (element | CRLF )*
element ::= openedElement | closedElement
openedElement ::= START_TAG_START TAG_NAME attributes? START_TAG_END elementContent? END_TAG_START TAG_NAME END_TAG_END
closedElement ::= START_TAG_START TAG_NAME attributes? EMPTY_ELEMENT_END
attributes ::= attribute+
attribute ::= ATTRIBUTE_NAME (EQ attributeValue)?
attributeValue ::= string
string ::= STRING_START string_text STRING_END
string_text ::= (exprInsert|STRING_CONTENT )*
exprInsert ::= LEFT_DOUBLE_BRACE EXPR? RIGHT_DOUBLE_BRACE
elementContent ::= (element | TEXT | exprInsert)*