{
  parserClass="com.zxy.ijplugin.wechat_miniprogram.lang.wxss.parser.WXSSParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="WXSS"
  psiImplClassSuffix="Impl"
  psiPackage="com.zxy.ijplugin.wechat_miniprogram.lang.wxss.psi"
  psiImplPackage="com.zxy.ijplugin.wechat_miniprogram.lang.wxss.psi.impl"

  elementTypeHolderClass="com.zxy.ijplugin.wechat_miniprogram.lang.wxss.psi.WXSSTypes"
  elementTypeClass="com.zxy.ijplugin.wechat_miniprogram.lang.wxss.psi.WXSSElementType"
  tokenTypeClass="com.zxy.ijplugin.wechat_miniprogram.lang.wxss.psi.WXSSTokenType"
}

wxssFile ::= (import | styleDefinition)*
import ::= (IMPORT_KEYWORD string SEMICOLON)
string ::= (STRING_START_DQ STRING_CONTENT STRING_END_DQ | STRING_START_SQ STRING_CONTENT STRING_END_SQ)
styleDefinition ::= (selectorGroup  styleStatementCollection)
selectorGroup ::= ()
styleStatementCollection ::=